POST http://localhost:8080/events 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZWxib2xha3kuZGV2IiwiZXhwIjoxNzE1NTc3ODAwLCJ1c2VySUQiOjF9.WHQvnjydYhk6yXTz3J-FQByQ3bI8TC3z6tfdGPgmF4I

{
  "Name": "A Very Special Day!",
  "Description": "A test post request to create event",
  "Location": "Test location",
  "DateTime": "2024-08-19T00:00:00.000Z"
}