POST http://localhost:8080/events 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVsYm9sYWt5LmRldiIsImV4cCI6MTcxNTU3OTk1NywidXNlcklEIjoyfQ.FsyZ1OzYN8mum5qrcjL_mS4urmCsbxCueUNr4ecjlWQ

{
  "Name": "A Very Special Day!",
  "Description": "A test post request to create event",
  "Location": "Test location",
  "DateTime": "2024-08-19T00:00:00.000Z"
}