PUT http://localhost:8080/events/8
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVsYm9sYWt5LmRldiIsImV4cCI6MTcxNTU4MTc0MSwidXNlcklEIjoyfQ.uCHqh9OyLUxNjv32yVZpfV3CDnr5r2uigwf3lJg7br0

{
  "Name": "I hope I'm with you!",
  "Description": "Updated A test post request to create event",
  "Location": "Updated Test location",
  "DateTime": "2024-10-24T00:00:00.000Z"
}